<?php

namespace Valkyrja\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;
use Valkyrja\Rules\LimitedRegExOrs;

class UpdateServerConfig extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        // Authorization handled elsewhere
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'ignore_bots'                       => 'boolean',
            'ignore_everyone'                   => 'boolean',
            'command_prefix'                    => 'string|max:255',
            'command_prefix_alt'                => 'string|max:255',
            'execute_on_edit'                   => 'boolean',
            'antispam_norole'                   => 'boolean',
            'antispam_username'                 => 'boolean',
            'antispam_invites'                  => 'boolean',
            'antispam_invites_ban'              => 'boolean',
            'antispam_porn'                     => 'boolean',
            'antispam_duplicate'                => 'boolean',
            'antispam_duplicate_crossserver'    => 'boolean',
            'antispam_duplicate_ban'            => 'boolean',
            'antispam_mentions_max'             => 'integer',
            'antispam_mentions_ban'             => 'boolean',
            'antispam_mute'                     => 'boolean',
            'antispam_mute_duration'            => 'integer',
            'antispam_links_extended'           => 'boolean',
            'antispam_links_extended_ban'       => 'boolean',
            'antispam_links_standard'           => 'boolean',
            'antispam_links_standard_ban'       => 'boolean',
            'antispam_links_youtube'            => 'boolean',
            'antispam_links_youtube_ban'        => 'boolean',
            'antispam_links_twitch'             => 'boolean',
            'antispam_links_twitch_ban'         => 'boolean',
            'antispam_links_hitbox'             => 'boolean',
            'antispam_links_hitbox_ban'         => 'boolean',
            'antispam_links_beam'               => 'boolean',
            'antispam_links_beam_ban'           => 'boolean',
            'antispam_links_imgur'              => 'boolean',
            'antispam_links_imgur_ban'          => 'boolean',
            'antispam_tolerance'                => 'integer',
            'antispam_ignore_members'           => 'boolean',
            'antispam_voice_switching'          => 'boolean',
            'operator_roleid'                   => 'integer',
            'quickban_duration'                 => 'integer',
            'quickban_reason'                   => 'string|nullable',
            'mute_roleid'                       => 'integer',
            'mute_ignore_channelid'             => 'integer',
            'karma_enabled'                     => 'boolean',
            'karma_limit_mentions'              => 'integer',
            'karma_limit_minutes'               => 'integer',
            'karma_limit_response'              => 'boolean',
            'karma_currency'                    => 'string|max:255',
            'karma_currency_singular'           => 'string|max:255',
            'karma_consume_command'             => 'string|max:255',
            'karma_consume_verb'                => 'string|max:255',
            'log_channelid'                     => 'integer',
            'alert_channelid'                   => 'integer',
            'mod_channelid'                     => 'integer',
            'tempchannel_categoryid'            => 'integer',
            'log_bans'                          => 'boolean',
            'log_promotions'                    => 'boolean',
            'log_deletedmessages'               => 'boolean',
            'log_editedmessages'                => 'boolean',
            'activity_channelid'                => 'integer',
            'log_join'                          => 'boolean',
            'log_leave'                         => 'boolean',
            'log_alert_regex'                   => ['string', 'nullable', new LimitedRegExOrs(20)],
            'log_message_join'                  => 'string|nullable',
            'log_message_leave'                 => 'string|nullable',
            'log_mention_join'                  => 'boolean',
            'log_mention_leave'                 => 'boolean',
            'log_timestamp_join'                => 'boolean',
            'log_timestamp_leave'               => 'boolean',
            'log_warnings'                      => 'boolean',
            'welcome_pm'                        => 'boolean',
            'welcome_message'                   => 'string|nullable',
            'welcome_roleid'                    => 'integer',
            'verify'                            => 'boolean',
            'verify_on_welcome'                 => 'boolean',
            'verify_roleid'                     => 'integer',
            'verify_karma'                      => 'integer',
            'verify_message'                    => 'string',
            'exp_enabled'                       => 'boolean',
            'base_exp_to_levelup'               => 'integer',
            'exp_announce_levelup'              => 'boolean',
            'exp_per_message'                   => 'integer',
            'exp_per_attachment'                => 'integer',
            'exp_max_level'                     => 'integer',
            'exp_cumulative_roles'              => 'boolean',
            'exp_advance_users'                 => 'boolean',
            'exp_member_roleid'                 => 'integer',
            'exp_member_messages'               => 'integer',
            'roles'                             => 'array',
            'roles.*'                           => 'array',
            'roles.*.roleid'                    => 'required|integer|min:0',
            'roles.*.permission_level'          => 'required|integer|between:0,5',
            'roles.*.public_id'                 => 'required|integer|min:0',
            'roles.*.antispam_ignored'          => 'required|boolean',
            'levels.*.roleid'                   => 'required|integer|min:0',
            'levels.*.level'                    => 'required|integer|min:0',
            'custom_commands'                   => 'array',
            'custom_commands.*'                 => 'required|array',
            'custom_commands.*.commandid'       => 'required|alpha_num|max:127',
            'custom_commands.*.response'        => 'required|string',
            'custom_commands.*.description'     => 'string',
            'voice_channelid'                   => 'integer',
            'embed_voicechannel'                => 'boolean',
            'embed_activitychannel'             => 'boolean',
            'embed_logchannel'                  => 'boolean',
            'embed_modchannel'                  => 'boolean',
            'color_voicechannel'                => 'regex:/^#([a-f0-9]{3}){1,2}\b/i',
            'color_activitychannel'             => 'regex:/^#([a-f0-9]{3}){1,2}\b/i',
            'color_logchannel'                  => 'regex:/^#([a-f0-9]{3}){1,2}\b/i',
            'color_alertchannel'                => 'regex:/^#([a-f0-9]{3}){1,2}\b/i',
            'color_modchannel'                  => 'regex:/^#([a-f0-9]{3}){1,2}\b/i',
            'color_logmessages'                 => 'regex:/^#([a-f0-9]{3}){1,2}\b/i',
            'color_logwarning'                  => 'regex:/^#([a-f0-9]{3}){1,2}\b/i',
            'channels'                          => 'array',
            'channels.*'                        => 'array',
            'channels.*.channelid'              => 'required|integer|min:0',
            'channels.*.ignored'                => 'boolean',
            'memo_enabled'                      => 'boolean',
            'profile_enabled'                   => 'boolean',
            'profile_options'                   => 'array',
            'profile_options.*'                 => 'array',
            'profile_options.*.option'          => 'required|string|max:100',
            'profile_options.*.option_alt'      => 'required|string|max:100',
            'profile_options.*.label'           => 'required|string|max:250',
            'profile_options.*.property_order'  => 'required|integer',
            'profile_options.*.inline'          => 'required|boolean',
            'profile_channelid'                 => 'integer',
            'role_groups'                       => 'array',
            'role_groups.*'                     => 'array',
            'role_groups.*.groupid'             => 'required|integer',
            'role_groups.*.role_limit'          => 'required|integer',
            'role_groups.*.name'                => 'present|string|nullable|max:250',
            'reaction_roles'                    => 'array',
            'reaction_roles.*'                  => 'array',
            'reaction_roles.*.*'                => 'array',
            'reaction_roles.*.*.roleid'         => 'required|integer',
            'reaction_roles.*.*.emoji'          => 'required|string|max:250',
        ];
    }
}
